# Generated by Django 3.1.6 on 2021-02-15 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlpviewer_backend', '0003_auto_20201010_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationlog',
            name='endTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 15, 4, 36, 16, 382949)),
        ),
        migrations.AlterField(
            model_name='annotationlog',
            name='startTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 15, 4, 36, 16, 382912)),
        ),
    ]
