# Generated by Django 3.1.6 on 2021-03-08 04:08

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nlpviewer_backend', '0004_auto_20210215_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationlog',
            name='endTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 7, 23, 8, 42, 936176)),
        ),
        migrations.AlterField(
            model_name='annotationlog',
            name='startTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 7, 23, 8, 42, 936141)),
        ),
        migrations.AlterField(
            model_name='crossdoc',
            name='packID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='packID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
